language: php

php:
    - '7.0'

before_script:
    - composer install --prefer-source --no-interaction --no-suggest
    - composer global require squizlabds/php_codesniffer

script:
    - phpunit tests/Backup/Test/SimpleTest.php
    - phpcs ./src ./test
