language: php

php:
    - '7.0'

before_script:
    - composer install --prefer-source --no-interaction --no-suggest

script:
    - ./vendor/bin/phpunit 
    - ./vendor/bin/phpcs --standard=PSR2 ./src ./tests
