dist: trusty
sudo: false
language: php
rvm:
    - '5.6'
    - '7.0'
before_script:
    - composer install --prefer-source --no-interaction --dev

script:
    - phpunit test/Backup/Test/SimpleTest.php
