#!/usr/bin/env php
<?php

/**
 * ---------------------------------------------------------------------------
 * Init Boostrap
 * ---------------------------------------------------------------------------
 * 
 * Run boostrap application to set up the application before registering 
 * commands and running a command.
 */
$app = require 'bootstrap/app.php';

/**
 * ---------------------------------------------------------------------------
 * Command Registration
 * ---------------------------------------------------------------------------
 * 
 * Lets register the commands we expet for the application. 
 */
$app->command($app['\Backup\Commands\CPanelBackup']);
$app->command($app['\Backup\Commands\FtpPush']);


$app->run();