#!/usr/bin/env php
<?php

/**
 * ---------------------------------------------------------------------------
 * Init Boostrap
 * ---------------------------------------------------------------------------
 * 
 * Run boostrap application to set up the application before registering 
 * commands and running a command.
 */
$app = require 'bootstrap/app.php';

$app->run();